# name: Publish Docker image

# on:
#   release:
#     types: [published]
#   push:
#     branches:
#       - main

# jobs:
#   push_to_registry:
#     name: Push Docker image to Docker Hub
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#         name: Check out code

#       # Required when overrideDriver is set to true
#       - uses: docker/setup-buildx-action@v2
#         name: Customize Docker driver
#         with:
#           driver-opts: image=moby/buildkit:v0.11.0

#       - uses: mr-smithers-excellent/docker-build-push@v6
#         name: Build & push Docker image
#         with:
#           image: jaylaelove/noc-pm25-interactive-2024
#           tags: latest
#           registry: docker.io
#           platform: linux/arm64,linux/amd64
#           overrideDriver: true
#           username: ${{ secrets.DOCKER_HUB_USERNAME }}
#           password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

name: Publish Docker image

on:
  release:
    types: [published]
  push:
    branches:
      - main

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: jaylaelove/noc-pm25-interactive-2024:latest
