name: Publish Docker image

on:
  release:
    types: [published]
  push:
    branches:
      - main

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Check out code

      # Required when overrideDriver is set to true
      - uses: docker/setup-buildx-action@v2
        name: Customize Docker driver
        with:
          driver-opts: image=moby/buildkit:v0.11.0

      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build & push Docker image
        with:
          image: jaylaelove/noc-pm25-interactive-2024
          tags: latest
          registry: docker.io
          platform: linux/arm64
          overrideDriver: true
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}



